### PR TITLE
Change Filezilla connection from ACI IP to ACI FQDN

### PR DESCRIPTION
**Pull request by macolso**
## Purpose

* ACI doesn't support static IPs, thus it is better practice to connect via FQDN in the event of a container restart. 

## Does this introduce a breaking change?

```
[ ] Yes
[X ] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[X ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[X] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
*  Follow the sample from start to finish 

```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
npm install
```

* Test the code

```
```

## What to Check
Verify that the following are valid
* ...

### CODE REVIEW

**Comment by macolso** [comment]
@RenaShahMSFT please review!

**Comment by bhummerstone** [comment]
Might also be worth updating the Outputs section to point to the dnsNameLabel instead of the IP address

**Comment by macolso** [comment]
Are you referring to the screen shot of Filezilla as the Outputs section, @bhummerstone??

**Comment by kummerer94** [comment]
Really cool changes. Would it be possible to make the FQDN a parameter the user can fill in before deployment?

**Comment by bhummerstone** [comment]
> Are you referring to the screen shot of Filezilla as the Outputs section, @bhummerstone??

Nope: changing the Outputs section of the ARM template to be the DNS FQDN as opposed to the public IP :)

**Comment by macolso** [comment]
@bhummerstone - updated the outputs section of the ARM template!
@kummerer94 - thanks! you can either modify the arm template directly and change the containerGroupDNSLabl default value to your desired FQDN or when this PR is merged Azure Portal view should include a field for the FQDN as well.

**Pull request merged**
